export const GET_LINK_DATA = "app/Home/GET_LINK_DATA";
export const GET_LINK_DATA_SUCCESS = "app/Home/GET_LINK_DATA_SUCCESS";
export const GET_LINK_DATA_FAILED = "app/Home/GET_LINK_DATA_FAILED";

export const GET_CATEGORIES = "app/Home/GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "app/Home/GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILED = "app/Home/GET_CATEGORIES_FAILED";
