export const LOGOUT = "app/App/LOGOUT";
export const DISPLAY_ALERT = "app/App/DISPLAY_ALERT";

export const SET_AUTHENTICATING = "app/App/SET_AUTHENTICATING";
export const SET_AUTHENTICATED = "app/App/SET_AUTHENTICATED";
export const SET_LOADING = "app/App/SET_LOADING";

export const ADD_CATEGORY = "app/App/ADD_CATEGORY";
export const ADD_CATEGORY_SUCCESS = "app/App/ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILED = "app/App/ADD_CATEGORY_FAILED";

export const REMOVE_CATEGORY = "app/App/REMOVE_CATEGORY";
export const REMOVE_CATEGORY_SUCCESS = "app/App/REMOVE_CATEGORY_SUCCESS";
export const REMOVE_CATEGORY_FAILED = "app/App/REMOVE_CATEGORY_FAILED";

export const RENAME_CATEGORY = "app/App/RENAME_CATEGORY";
export const RENAME_CATEGORY_SUCCESS = "app/App/RENAME_CATEGORY_SUCCESS";
export const RENAME_CATEGORY_FAILED = "app/App/RENAME_CATEGORY_FAILED";

export const GET_CATEGORIES = "app/App/GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "app/App/GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILED = "app/App/GET_CATEGORIES_FAILED";

export const GET_TRASH = "app/App/GET_TRASH";
export const GET_TRASH_SUCCESS = "app/App/GET_TRASH_SUCCESS";
export const GET_TRASH_FAILED = "app/App/GET_TRASH_FAILED";

export const GET_CATEGORY_LINKS = "app/App/GET_CATEGORY_LINKS";
export const GET_CATEGORY_LINKS_SUCCESS = "app/App/GET_CATEGORY_LINKS_SUCCESS";
export const GET_CATEGORY_LINKS_FAILED = "app/App/GET_CATEGORY_LINKS_FAILED";
